apiVersion: v1
kind: Namespace
metadata:
  name: openshift-serverless
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: serverless-operator
  namespace: openshift-marketplace
spec:
  displayName: Serverless Operator
  image: registry.ci.openshift.org/knative/main:serverless-index
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: serverless
  namespace: openshift-serverless
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: "serverless-operator"
  namespace: "openshift-serverless"
spec:
  channel: "stable"
  name: "serverless-operator"
  source: "serverless-operator"
  sourceNamespace: "openshift-marketplace"
  installPlanApproval: Automatic
